### ISSUE TITLE
Is this software still alive

### ISSUE THREAD

**Issue by ostcar** [kylehuff/webpg-chrome#111]
I'am wondering if this software is still developed. I could not find it in the Google Chrome Webstore. The link on the project page does not work. Is there any way to install webpg on chrome at the current moment or in the near future?

**Comment by deed02392** [comment]
Did you try to download the zip: https://github.com/kylehuff/webpg-chrome on the right side and 'load unpacked extension' in Chrome?

**Comment by ostcar** [comment]
This does not work. I get the message:
"Fehler beim Laden der Erweiterung aus: /tmp/webpg-chrome-master_5hSTrF.Manifest-Datei fehlt oder ist nicht lesbar."

Which could be in English:
"Failed to load extension from: /tmp/webpg-chrome-master_5hSTrF.Manifest-File is missing or is not readable"

I am not sure if you addon can work with Chrome. This document says:
"September 2015

In September 2015 (Chrome 45) we will remove the override and NPAPI support will be permanently removed from Chrome. Installed extensions that require NPAPI plugins will no longer be able to load those plugins."
https://www.chromium.org/developers/npapi-deprecation

So until #102 is fixed, you extension should not work with Chrome anymore. But I could not install the extension and therefore could not test it.

**Comment by kylehuff** [comment]
The plugin has moved from NPAPI to Native Messaging for chrome.  I am
finalizing the remaining changes as time allows, and I will be releasing a
new version (in the chrome webstore, and the website) as soon as I can.

Later today I will try to publish a guide on how to get, install and test
the latest version, so the appropriate testing can occur prior to release.

Kyle L. Huff
http://curetheitch.com
http://webpg.org

**Comment by ostcar** [comment]
Any update on the nativeMessaging support?

I am interested in this change because I work together with a group of people on a project, where we analyse how gnupg can be used as Browser extension for Chrome and Firefox: http://wiki.gnupg.org/Gpg4all2015

You extensions seems to be the only one, that could be used at the moment.

**Comment by baryluk** [comment]
Any updates?

**Comment by darkpixel** [comment]
I can't give you an official answer, but I'm pretty sure @kylehuff has been pretty busy for the last few months with $dayjob.

**Comment by dhyannataraj** [comment]
Signed for notifications. I am also interested in this extention...
